testa: scratchcardsa.c
	clang scratchcardsa.c -o scrat
	./scrat test_input.dat

fulla: scratchcardsa.c
	clang scratchcardsa.c -o scrat
	./scrat full_input.dat

testb: scratchcardsb.c
	clang scratchcardsb.c -o scrat
	./scrat test_input.dat

fullb: scratchcardsb.c
	clang scratchcardsb.c -o scrat
	./scrat full_input.dat
