testA:
	clang coexa.c -DTEST=1 -o coex
	./coex test_inputa.dat

testList:
	clang testList.c -o tl
	./tl

fullA:
	clang coexa.c -o coex
	./coex full_input.dat

testB:
	clang coexb.c -DTEST=1 -o coex
	./coex test_inputa.dat

fullB:
	clang coexb.c -o coex
	./coex full_input.dat


