testA:
	clang hawea.c -o hawe
	./hawe test_input.dat

fullA:
	clang hawea.c -o hawe
	./hawe full_input.dat

testB:
	clang haweb.c -o hawe
	./hawe test_inputb.dat


fullB:
	clang haweb.c -o hawe
	./hawe full_input.dat


