testA:
	clang mimaa.c -DTEST=1 -o mima
	./mima test_inputa.dat

fullA:
	clang mimaa.c -o mima
	./mima full_input.dat

testB:
	clang mimab.c -DTEST=1 -o mima
	./mima test_inputa.dat

fullB:
	clang mimab.c -o mima
	./mima full_input.dat


