testA:
	clang pimaa.c -DTEST=5 -o pima
	./pima test_inputa.dat

fullA:
	clang pimaa.c -o pima
	./pima full_input.dat

testB:
	clang pimab.c -DTEST=5 -o pima
	./pima test_inputb.dat

fullB:
	clang pimab.c -o pima
	./pima full_input.dat
