testA:
	clang wfia.c -o wfi
	./wfi test_input.dat
fullA:
	clang wfia.c -o wfi
	./wfi full_input.dat
testB:
	clang wfib.c -o wfi
	./wfi test_input.dat
fullB:
	clang wfib.c -o wfi
	./wfi full_input.dat
