testA:
	clang cardsa.c -o cards
	./cards test_input.dat

fullA:
	clang cardsa.c -o cards
	./cards full_input.dat

testB:
	clang cardsb.c -o cards
	./cards test_input.dat

fullB:
	clang cardsb.c -o cards
	./cards full_input.dat


