testA:
	clang iygasafa.c -o iygasaf
	./iygasaf test_input.dat

fullA:
	clang iygasafa.c -o iygasaf
	./iygasaf full_input.dat

testB:
	clang iygasafb.c -o iygasaf
	./iygasaf test_input.dat

fullB:
	clang iygasafb.c -o iygasaf
	./iygasaf full_input.dat



